apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditation-api
  namespace: meditation-app
  labels:
    app: meditation-api
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meditation-api
  template:
    metadata:
      labels:
        app: meditation-api
        version: v1.0.0
    spec:
      containers:
      - name: meditation-api
        image: meditation-app/api:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5