apiVersion: v1
kind: Service
metadata:
  name: meditation-api-service
  namespace: meditation-app
  labels:
    app: meditation-api
spec:
  selector:
    app: meditation-api
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP